setTimeout(() => {
    console.log("Hacking wifi.....please wait...")
}, 1000)
try {
    // setTimeout(() => {
        console.log(rahul)
    // }, 100)
}
// if settimeout is defined in try and catch it has error then 
// it is not going to resolved it works for synchronous only to avoid this we need to again use try and catch in settimeout
catch (error) {
    console.log("jai shree Ram")
}
setTimeout(() => {
    console.log("fetching username and password.....please wait...")
}, 2000)
setTimeout(() => {
    console.log("Hacking Rahul's facebook id.....please wait...")
}, 3000)
setTimeout(() => {
    console.log("Username and password of Rahul fetched (+9194605983990000).....please wait...")
}, 4000)
